# Generated by Django 5.1.4 on 2026-01-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='embeddingchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='uq_embeddingchunk_doc_chunk'),
        ),
    ]
