# Generated by ChatGPT patch
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copilot", "0004_embeddingchunk_add_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="idempotencykey",
            name="response_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
