# Generated by Django 5.1.4 on 2026-01-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0005_idempotencykey_response_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
